### ISSUE TITLE
"Automatically show Display" does not switch image

### ISSUE THREAD

**Issue by propri** [Evannessa/Journal-To-Canvas-Slideshow#34]
How to reproduce:

1. The option "Automatically show Display" is activated
2. An image is displayed in the display scene
3. Another scene than the display scene is active
4. Clicking a different image in a journal

Result:  
The display scene is activated, but the old image is still displayed. Another click on the new image is needed to change the displayed image.

Expected behavior:  
Clicking an image once is enough to both change to the display scene and show the new image.

**Comment by EvanesceExotica** [comment]
Hello! So sorry for the delay in my reply.

This module has just received a huge update that involved an overhaul of the entire code-base.

While the currently published version (v 2.1) doesn't have the "automatically show display" functionality added back in just yet, I am working on a pre-release version that involves support for Foundry v10 (and backwards compatibility for v9), where I've added that functionality back in and it can be configured in the settings. 

I recommend giving the latest published version (v2.1) a try to see if it suits your needs without that option, as a lot of additional features have been added, but if it doesn't, you can try installing the pre-release experimental version by pasting the link below:

https://raw.githubusercontent.com/EvanesceExotica/Journal-To-Canvas-Slideshow/v10-migration-experimental/module.json

Into the textbox box at the bottom of the "Install Modules" window and clicking install.

![manifest url install instructions](https://user-images.githubusercontent.com/13098820/194425457-beb800fb-20cf-4de3-a448-80291c7af4fa.png)

Let me know if either of those options fix this issue for you. Thanks so much for your patience!

**Comment by propri** [comment]
I haven't used it for a while. Using the "show image in chosen art scene" button now activates the display as expected.

Fixed for me, thanks very much!
